### ISSUE TITLE
yarn安装node包总是报node-sass安装失败的问题以及解决方法

### ISSUE THREAD

**Issue by yoowinsu** [yoowinsu/blog#75]
好几次都是下面这样的报错：
```
$ yarn
yarn install v1.5.1
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
warning babel-preset-es2015@6.24.1: ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
[3/5] Fetching packages...
info fsevents@1.2.3: The platform "win32" is incompatible with this module.
info "fsevents@1.2.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[1/1] 鉅▒ node-sass: gyp ERR! not ok
[-/1] 鉅▒ waiting...
[-/1] 鉅▒ waiting...
[-/1] 鉅▒ waiting...
error An unexpected error occurred: "C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\
ode-sass: Command failed.
Exit code: 1
Command: C:\\Windows\\system32\\cmd.exe
Arguments: /d /s /c node scripts/build.js
Directory: C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\
ode-sass
Output:
Building: C:\\Program Files\
odejs\
ode.exe C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\
ode-gyp\\bin\
ode-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\\\Program Files\\\
odejs\\\
ode.exe',
gyp verb cli   'C:\\\\Users\\\\Administrator\\\\Desktop\\\\vue2-elm\\\
ode_modules\\\
ode-gyp\\\\bin\\\
ode-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing \"build\" directory
gyp verb command configure []
gyp verb check python checking for Python executable \"python2\" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:13:12)
gyp verb `which` failed     at F (C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:68:19)
gyp verb `which` failed     at E (C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:80:29)
gyp verb `which` failed     at C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:89:16
gyp verb `which` failed     at C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\isexe\\index.js:42:5
gyp verb `which` failed     at C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\isexe\\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:13:12)
gyp verb `which` failed     at F (C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:68:19)
gyp verb `which` failed     at E (C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:80:29)
gyp verb `which` failed     at C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:89:16
gyp verb `which` failed     at C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\isexe\\index.js:42:5
gyp verb `which` failed     at C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\isexe\\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\
    at getNotFoundError (C:\\\\Users\\\\Administrator\\\\Desktop\\\\vue2-elm\\\
ode_modules\\\\which\\\\which.js:13:12)\
    at F (C:\\\\Users\\\\Administrator\\\\Desktop\\\\vue2-elm\\\
ode_modules\\\\which\\\\which.js:68:19)\
    at E (C:\\\\Users\\\\Administrator\\\\Desktop\\\\vue2-elm\\\
ode_modules\\\\which\\\\which.js:80:29)\
    at C:\\\\Users\\\\Administrator\\\\Desktop\\\\vue2-elm\\\
ode_modules\\\\which\\\\which.js:89:16\
    at C:\\\\Users\\\\Administrator\\\\Desktop\\\\vue2-elm\\\
ode_modules\\\\isexe\\\\index.js:42:5\
    at C:\\\\Users\\\\Administrator\\\\Desktop\\\\vue2-elm\\\
ode_modules\\\\isexe\\\\windows.js:36:5\
    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable \"python\" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:13:12)
gyp verb `which` failed     at F (C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:68:19)
gyp verb `which` failed     at E (C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:80:29)
gyp verb `which` failed     at C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:89:16
gyp verb `which` failed     at C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\isexe\\index.js:42:5
gyp verb `which` failed     at C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\isexe\\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:13:12)
gyp verb `which` failed     at F (C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:68:19)
gyp verb `which` failed     at E (C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:80:29)
gyp verb `which` failed     at C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\which\\which.js:89:16
gyp verb `which` failed     at C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\isexe\\index.js:42:5
gyp verb `which` failed     at C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\isexe\\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\
    at getNotFoundError (C:\\\\Users\\\\Administrator\\\\Desktop\\\\vue2-elm\\\
ode_modules\\\\which\\\\which.js:13:12)\
    at F (C:\\\\Users\\\\Administrator\\\\Desktop\\\\vue2-elm\\\
ode_modules\\\\which\\\\which.js:68:19)\
    at E (C:\\\\Users\\\\Administrator\\\\Desktop\\\\vue2-elm\\\
ode_modules\\\\which\\\\which.js:80:29)\
    at C:\\\\Users\\\\Administrator\\\\Desktop\\\\vue2-elm\\\
ode_modules\\\\which\\\\which.js:89:16\
    at C:\\\\Users\\\\Administrator\\\\Desktop\\\\vue2-elm\\\
ode_modules\\\\isexe\\\\index.js:42:5\
    at C:\\\\Users\\\\Administrator\\\\Desktop\\\\vue2-elm\\\
ode_modules\\\\isexe\\\\windows.js:36:5\
    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find \"python\". checking python launcher
gyp verb could not find \"python\". guessing location
gyp verb ensuring that file exists: C:\\Python27\\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable \"python\", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\
ode-gyp\\lib\\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\
ode-gyp\\lib\\configure.js:508:16)
gyp ERR! stack     at C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\\graceful-fs\\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command \"C:\\\\Program Files\\\
odejs\\\
ode.exe\" \"C:\\\\Users\\\\Administrator\\\\Desktop\\\\vue2-elm\\\
ode_modules\\\
ode-gyp\\\\bin\\\
ode-gyp.js\" \"rebuild\" \"--verbose\" \"--libsass_ext=\" \"--libsass_cflags=\" \"--libsass_ldflags=\" \"--libsass_library=\"
gyp ERR! cwd C:\\Users\\Administrator\\Desktop\\vue2-elm\
ode_modules\
ode-sass
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
```

## 解决办法

* npm：
```
npm config set sass-binary-site http://npm.taobao.org/mirrors/node-sass
```
* yarn：
```
yarn config set sass-binary-site http://npm.taobao.org/mirrors/node-sass
```

**Comment by yoowinsu** [comment]
安装`puppeteer`报错
```
ERROR: Failed to download Chromium r637110! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
```
解决办法
添加`.npmrc`文件指定下载源为淘宝镜像
`.npmrc`代码为

```
puppeteer_download_host=https://storage.googleapis.com.cnpmjs.org
```
